module Evergreen.Migrate.V2 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Evergreen.V1.Types
import Evergreen.V2.Types
import Lamdera.Migrations exposing (..)
import Maybe


frontendModel : Evergreen.V1.Types.FrontendModel -> ModelMigration Evergreen.V2.Types.FrontendModel Evergreen.V2.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V1.Types.BackendModel -> ModelMigration Evergreen.V2.Types.BackendModel Evergreen.V2.Types.BackendMsg
backendModel old =
    ModelMigrated ( migrate_Types_BackendModel old, Cmd.none )


frontendMsg : Evergreen.V1.Types.FrontendMsg -> MsgMigration Evergreen.V2.Types.FrontendMsg Evergreen.V2.Types.FrontendMsg
frontendMsg old =
    MsgUnchanged


toBackend : Evergreen.V1.Types.ToBackend -> MsgMigration Evergreen.V2.Types.ToBackend Evergreen.V2.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V1.Types.BackendMsg -> MsgMigration Evergreen.V2.Types.BackendMsg Evergreen.V2.Types.BackendMsg
backendMsg old =
    MsgMigrated ( migrate_Types_BackendMsg old, Cmd.none )


toFrontend : Evergreen.V1.Types.ToFrontend -> MsgMigration Evergreen.V2.Types.ToFrontend Evergreen.V2.Types.FrontendMsg
toFrontend old =
    MsgMigrated ( migrate_Types_ToFrontend old, Cmd.none )


migrate_Types_BackendModel : Evergreen.V1.Types.BackendModel -> Evergreen.V2.Types.BackendModel
migrate_Types_BackendModel old =
    { circles = (Unimplemented {- Type `List (Evergreen.V2.Types.ColorCircle)` was added in V2. I need you to set a default value. -})
    , sections = (Unimplemented {- Field of type `List (Evergreen.V1.Types.ColorSection)` was removed in V2. I need you to do something with the `old.sections` value if you wish to keep the data, then remove this line. -})
    }


migrate_Types_FrontendModel : Evergreen.V1.Types.FrontendModel -> Evergreen.V2.Types.FrontendModel
migrate_Types_FrontendModel old =
    { selectedColor = old.selectedColor |> Maybe.map migrate_Types_Color
    , circles = (Unimplemented {- Type `List (Evergreen.V2.Types.ColorCircle)` was added in V2. I need you to set a default value. -})
    , sections = (Unimplemented {- Field of type `List (Evergreen.V1.Types.ColorSection)` was removed in V2. I need you to do something with the `old.sections` value if you wish to keep the data, then remove this line. -})
    }


migrate_Types_BackendMsg : Evergreen.V1.Types.BackendMsg -> Evergreen.V2.Types.BackendMsg
migrate_Types_BackendMsg old =
    case old of
        Evergreen.V1.Types.ClientConnected p0 p1 ->
            Evergreen.V2.Types.ClientConnected p0 p1

        Evergreen.V1.Types.NewSection p0 ->
            (Unimplemented
             {- `NewSection` was removed or renamed in V2 so I couldn't figure out how to migrate it.
                I need you to decide what happens to this Evergreen.V1.Types.NewSection value in a migration.
                See https://dashboard.lamdera.app/tips/modified-custom-type for more info.
             -}
            )

        notices ->
            {- @NOTICE `NewCircle Evergreen.V2.Types.ColorCircle` was added in V2.
               This is just a reminder in case migrating some subset of the old data to this new value was important.
               See https://dashboard.lamdera.app/tips/modified-custom-type for more info.
            -}
            (Unimplemented {- New constructors were added. I need you to resolve the above notices and then remove this case. -})


migrate_Types_Color : Evergreen.V1.Types.Color -> Evergreen.V2.Types.Color
migrate_Types_Color old =
    case old of
        Evergreen.V1.Types.Color1 ->
            Evergreen.V2.Types.Color1

        Evergreen.V1.Types.Color2 ->
            Evergreen.V2.Types.Color2

        Evergreen.V1.Types.Color3 ->
            Evergreen.V2.Types.Color3

        Evergreen.V1.Types.Color4 ->
            Evergreen.V2.Types.Color4

        Evergreen.V1.Types.Color5 ->
            Evergreen.V2.Types.Color5


migrate_Types_ColorCircle : Evergreen.V1.Types.ColorSection -> Evergreen.V2.Types.ColorCircle
migrate_Types_ColorCircle old =
    { color = old.color |> migrate_Types_Color
    , size = (Unimplemented {- Type `Float` was added in V2. I need you to set a default value. -})
    , width = (Unimplemented {- Field of type `Float` was removed in V2. I need you to do something with the `old.width` value if you wish to keep the data, then remove this line. -})
    , x = (Unimplemented {- Field of type `Float` was removed in V2. I need you to do something with the `old.x` value if you wish to keep the data, then remove this line. -})
    }


migrate_Types_ToFrontend : Evergreen.V1.Types.ToFrontend -> Evergreen.V2.Types.ToFrontend
migrate_Types_ToFrontend old =
    case old of
        Evergreen.V1.Types.SectionAdded p0 ->
            (Unimplemented
             {- `SectionAdded` was removed or renamed in V2 so I couldn't figure out how to migrate it.
                I need you to decide what happens to this Evergreen.V1.Types.SectionAdded value in a migration.
                See https://dashboard.lamdera.app/tips/modified-custom-type for more info.
             -}
            )

        Evergreen.V1.Types.InitialState p0 ->
            Evergreen.V2.Types.InitialState (p0 |> List.map migrate_Types_ColorCircle)

        Evergreen.V1.Types.CanvasCleared ->
            Evergreen.V2.Types.CanvasCleared

        notices ->
            {- @NOTICE `CircleAdded Evergreen.V2.Types.ColorCircle` was added in V2.
               This is just a reminder in case migrating some subset of the old data to this new value was important.
               See https://dashboard.lamdera.app/tips/modified-custom-type for more info.
            -}
            (Unimplemented {- New constructors were added. I need you to resolve the above notices and then remove this case. -})
